# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us

zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 简历网站
  params:
    description: 个人简历与博客
  menu:
    main:
      - name: 简历
        url: /
        weight: 10
      - name: 博客
        url: blog/
        weight: 20
      - name: 其他
        url: uses/
        weight: 30
